# yamllint disable rule:line-length
---
version: "3"

vars:
  image: internal/ci-base
  tags: latest 5.2 5.0
  platform: '{{.BUILD_PLATFORM | default "linux/amd64"}}'

env:
  DOCKER_BUILDKIT: 1
  BUILDX_EXPERIMENTAL: 1

tasks:
  default:
    desc: "Build docker images"
    vars:
      args: --rm --platform {{.platform}} --progress=plain --no-cache --pull
    cmds:
      - for:
          var: tags
          as: tag
        cmd: docker build {{.args}} -t {{.image}}:{{.tag}} -f {{.tag}}/Dockerfile {{.tag}}/

  enter:
    desc: "Run container shell"
    vars:
      tag: latest
    cmds:
      - docker run --rm -it {{.image}}:{{.tag}}

  info:
    desc: "Print image info"
    cmds:
      - for:
          var: tags
          as: tag
        cmd: |
          docker run --rm {{.image}}:{{.tag}} python3 -V
          docker run --rm {{.image}}:{{.tag}} go version
          docker run --rm {{.image}}:{{.tag}} go env | grep pkg

  diff:
    desc: "Print image diffs"
    cmds:
      - diff -uHr 5.0 5.2 || true
      - diff -uHr 5.2 latest || true
