# yamllint disable rule:line-length
---

name: 'Checkout PR'

description: >-
  Checkout last commit from source repository

inputs:
  jobname:
    default: ${{ github.job }}

runs:
  using: "composite"
  steps:
    - name: 'Checkout PR branch last commit'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        submodules: true
        lfs: true
