# yamllint disable rule:line-length
---

name: 'Run gotestsum'

description: >-
  Run gotestsum with retry options against all packages

inputs:
  jobname:
    default: ${{ github.job }}

  # Tags to include (csv)
  tags:
    default: ''

  # Arguments for `go test` (-race, etc.)
  args:
    defaults: ''

  # Loop through the packages
  loop:
    default: 'yes'

runs:
  using: "composite"
  steps:
    - name: 'Install gotestsum'
      shell: 'bash'
      run: go install gotest.tools/gotestsum@latest

    - name: 'Run gotestsum on all packages'
      shell: 'bash'
      if: ${{ inputs.loop != 'yes' }}
      run: |
        gotestsum --junitfile coverage-report.xml --rerun-fails=3 --raw-command \
        go test -tags=${{ inputs.tags }} ${{ inputs.args }} -json -timeout 15m -coverprofile=coverage-report.cov ./...

    - name: 'Run gotestsum on each package'
      shell: 'bash'
      if: ${{ inputs.loop == 'yes' }}
      run: |
        package=$(go list .)
        packages=$(go list ./... | tail -n +2 | sed -e "s|$package/||g")
        for pkg in ${packages}; do
            coveragefile=${pkg//\//-}
            gotestsum --junitfile ${coveragefile}.xml --rerun-fails=3 --raw-command \
            go test -tags=${{ inputs.tags }} ${{ inputs.args }} -json -timeout 15m -coverprofile=${coveragefile}.cov ./${pkg}
        done
