# yamllint disable rule:line-length
---
name: "Run go tests"

# This github workflow runs the minimal build checks that are required to
# pass for any change. It builds the project and the tests, making sure
# they both compile. The tests incidentally run all the `init` functions,
# initiating connections to redis.

on:  # yamllint disable-line rule:truthy
  workflow_call:

    # Require ORG_GH_TOKEN to access private repositories.
    secrets:
      ORG_GH_TOKEN:
        required: true

    # Customize inputs from source repository invocation.
    inputs:
      go-version:
        type: string
        default: "1.19.x"
      redis-version:
        type: string
        default: "6"
      python-version:
        type: string
        default: "3.9"

env:
  # Declare GOPRIVATE to enable fetching private repo packages.
  GOPRIVATE: github.com/TykTechnologies

jobs:
  test:
    name: "Test: Go ${{ inputs.go-version }} Redis ${{ inputs.redis-version }}"
    runs-on: ubuntu-latest

    steps:
      - name: "Use GitHub token"
        env:
          TOKEN: ${{ secrets.ORG_GH_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: "Checkout repository"
        uses: TykTechnologies/tyk-github-actions/.github/actions/checkout@main

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Start Redis"
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ inputs.redis-version }}

      - name: "Configure Go Cache"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: "Install base dependencies"
        run: |
          sudo apt-get install libluajit-5.1-dev
          python -m pip install --upgrade pip
          pip install setuptools
          pip install google
          pip install protobuf

      - name: "Run tests"
        uses: TykTechnologies/tyk-github-actions/.github/actions/gotestsum@main
        env:
          PYTHON_VERSION: ${{ inputs.python-version }}
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        with:
          tags: "goplugin"
          args: "-race -count=1"
