# yamllint disable rule:line-length
---
name: "Run go tests"

# This github workflow runs the minimal build checks that are required to
# pass for any change. It builds the project and the tests, making sure
# they both compile. The tests incidentally run all the `init` functions,
# initiating connections to redis.

on:  # yamllint disable-line rule:truthy
  workflow_call:

    # Require ORG_GH_TOKEN to access private repositories.
    secrets:
      ORG_GH_TOKEN:
        required: true

    # Customize inputs from source repository invocation.
    inputs:
      redis-version:
        type: string
        default: "6"

env:
  # Declare GOPRIVATE to enable fetching private repo packages.
  GOPRIVATE: github.com/TykTechnologies

jobs:
  test:
    name: "Test: Redis ${{ inputs.redis-version }}"
    runs-on: ubuntu-latest
    container: tykio/ci-base:5.2

    steps:
      - name: "Use GitHub token"
        env:
          TOKEN: ${{ secrets.ORG_GH_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: "Checkout repository"
        uses: TykTechnologies/tyk-github-actions/.github/actions/checkout@main

      - name: "Start Redis"
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ inputs.redis-version }}

      - name: "Configure Go Cache"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: 'Extract tykio/ci-tools'
        uses: shrink/actions-docker-extract@v3
        with:
          image: tykio/ci-tools:latest
          path: /usr/local/bin/.
          destination: /usr/local/bin

      - name: "Build test plugin"
        run: |
          go build -race -o ./test/goplugins/goplugins.so -buildmode=plugin ./test/goplugins

      - name: "Run tests"
        uses: TykTechnologies/tyk-github-actions/.github/actions/gotestsum@main
        env:
          TYK_GW_STORAGE_HOST: localhost
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        with:
          tags: "goplugin"
          args: "-race -count=1"
