# yamllint disable rule:line-length
---
name: "Pre-flight checks"

# This github workflow runs the minimal build checks that are required to
# pass for any change. It builds the project and the tests, making sure
# they both compile. The tests incidentally run all the `init` functions,
# initiating connections to redis.

on:  # yamllint disable-line rule:truthy
  workflow_call:

    # Require ORG_GH_TOKEN to access private repositories.
    secrets:
      ORG_GH_TOKEN:
        required: true

    # Customize inputs from source repository invocation.
    inputs:
      go-version:
        type: string
        default: "1.19.x"
      redis-version:
        type: string
        default: "6"

env:
  # Declare GOPRIVATE to enable fetching private repo packages.
  GOPRIVATE: github.com/TykTechnologies

jobs:
  preflight:
    name: "POC: Go ${{ inputs.go-version }} Redis ${{ inputs.redis-version }}"
    runs-on: ubuntu-latest

    steps:
      - name: "Use GitHub token"
        env:
          TOKEN: ${{ secrets.ORG_GH_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: "Checkout repository"
        uses: ./.github/actions/checkout@main

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}

      - name: "Start Redis"
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ inputs.redis-version }}

      - name: "Configure Go Cache"
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: "Build project"
        run: go build .

      - name: "Build project tests"
        run: go test -run=^$ ./...
