name: Docker - CI tooling for GitHub Actions

# This workflow builds the CI tooling from docker/tools/
# within this repository. It runs whenever a file inside
# is modified, and on a weekly schedule to get updates.

on:
  push:
    paths:
      - 'docker/tools/**'
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at 12:00 AM UTC
  pull_request:

jobs:
  tools-latest:
    name: 'Build tykio/ci-tools:${{ matrix.tag }}'
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 'latest'

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
            
    - name: 'Build tykio/ci-tools:latest'
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.ref_name == 'main' }}
        pull: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: docker/tools/latest
        tags: tykio/ci-tools:latest
