# yamllint disable rule:line-length
---
name: "Pre-flight checks"

# This github workflow runs the minimal build checks that are required to
# pass for any change. It builds the project.

on:  # yamllint disable-line rule:truthy
  workflow_call:

    # Require GitHub App credentials to generate tokens for private repositories.
    secrets:
      PROBE_APP_ID:
        required: true
      PROBE_APP_PRIVATE_KEY:
        required: true

    # Customize inputs from source repository invocation.
    inputs:
      release:
        type: string
        default: "5.2"

env:
  # Declare GOPRIVATE to enable fetching private repo packages.
  GOPRIVATE: github.com/TykTechnologies

jobs:
  preflight:
    name: "Preflight checks"
    runs-on: ubuntu-latest
    container:
      image: tykio/ci-base:${{ inputs.release }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    timeout-minutes: 10

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - name: "Use GitHub token"
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: "Checkout repository"
        uses: TykTechnologies/tyk-github-actions/.github/actions/checkout@main
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: "Configure Go Cache"
        uses: actions/cache@v3
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-preflight-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-preflight-

      - name: "Build project"
        run: go build .
